# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint
### Not For Grading

## Objective 

At the end of this experiment, you will be able to :

* Use Numpy Library

### 1. Import the numpy package under the name np

Hint: import â€¦ as

In [ ]:
# YOUR CODE HERE

### 2. Print the numpy version and the configuration

Hint: `np.__version__`, `np.show_config()`

In [ ]:
# YOUR CODE HERE

### 3: Create an array of 10 zeros

Hint:: np.zeros

In [ ]:
# YOUR CODE HERE

### 4. Create an array of 10 zeros where the fifth element value is set to 1

Hint: array[4]

In [ ]:
# YOUR CODE HERE

### 5. Create an array with values ranging from 10 to 49 (inclusive) and reverse it

Hint: arange

In [ ]:
# YOUR CODE HERE

### 6. Find indices of non-zero elements from [1, 2, 0, 0, 4, 0]

Hint: np.nonzero

In [ ]:
# YOUR CODE HERE

### 7. Create a 3x3 identity matrix

Hint: np.eye

In [ ]:
# YOUR CODE HERE

### 8. Create a 3x3x3 array with random values 

Hint: np.random.random

In [ ]:
# YOUR CODE HERE

### 9. Create an array of all the even numbers from 30 to 70 (inclusive)

In [ ]:
# YOUR CODE HERE

### 10. Generate 10x10 array with random integers between 0 to 4 (inclusive) and find the minimum and maximum values

Hint: min, max

In [ ]:
# YOUR CODE HERE

### 11. Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal

Hint: np.diag

In [ ]:
# YOUR CODE HERE

### 12: Create an array with values ranging from 20 to 39 (inclusive). Calculate the square root of elements in it.

Hint: np.sqrt( )

In [ ]:
# YOUR CODE HERE

### 13. Transpose the given array [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
Hint: np.transpose()

In [ ]:
# YOUR CODE HERE

### 14. Inverse the given array [[3, 4], [5, 6]]
Hint: np.linalg.inv()

In [ ]:
# YOUR CODE HERE

### 15. Concatenate two given arrays by columnwise (specify axis = 1)
Hint:  np.concatenate()

In [ ]:
c = np.array([[1, 2],[3, 4]])
d = np.array([[5, 6],[7, 8]])

# YOUR CODE HERE

### 16.Transpose the given arrays and concatenate by columnwise (specify axis = 1)
Hint: np.concatenate()

In [ ]:
a = np.array([[1,2],[3,4]])
d = np.array([[5,6],[7,8]])

# YOUR CODE HERE

### 17. For a given array, print second and third column

In [ ]:
a = np.array([[2, 4, 6, 8, 10], 
              [3, 6, 9, 12, 15], 
              [4, 8, 12, 16, 20]]) 

# YOUR CODE HERE

### 18. For a given array, print the values of the second and third rows from the second column.

In [ ]:
a = np.array([[10, 11, 12, 13, 14],
               [15, 16, 17, 18, 19],
               [20, 21, 22, 23, 24],
               [25, 26, 27, 28, 29],
               [30, 31, 32, 33, 34]])

# YOUR CODE HERE

### 19. For a given array perform the following:
#### 1. Calculate mean row wise and column wise by specifying respective axis
#### 2. What is the average value of array

In [ ]:
# 2D array  
array = np.array([[2, 4, 6, 8, 10], 
                  [3, 6, 9, 12, 15], 
                  [4, 8, 12, 16, 20]]) 

# YOUR CODE HERE

### 20. For a given array, get the slice of the first row from all the 3 matrices and print them.

In [ ]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]], 
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]], 
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])

# YOUR CODE HERE