# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

## Learning Objective



At the end of this experiment, you will be able to :

* Use Pandas Library

## Dataset

### Description

The dataset choosen for this exercise is an employee dataset. The dataset contains the following information regarding a particular employee:

* Emp ID
* Name Prefix
* First Name
* Middle Initial
* Last Name
* Gender 
* E Mail
* Father's Name
* Mother's Name
* Mother's Maiden Name
* Date of Birth
* Time of Birth
* Age in Yrs
*  Weight in Kgs
* Date of Joining
* Quarter of Joining
* Half of Joining 
* Year of Joining
* Month of Joining
* Month Name of Joining
* Short Month
* Day of Joining
* DOW of Joining
* Short DOW
* Age in Company (Years)
* Salary
* Last % Hike
* SSN
* Phone No
* Place Name
* CountyCity,
* State
* Zip
* Region
* User Name
* Password

In [ ]:
!  wget https://cdn.talentsprint.com/aiml/Experiment_related_data/Employee.csv

## Exercise 1

### a) Load the dataset with index as 'Emp ID'

In [ ]:
import pandas as pd
dataset = "Employee.csv"
df = pd.read_csv(dataset, index_col= 'Emp ID')

In [ ]:
df.shape

### b) Display the first 5 entries of the dataset

In [ ]:
df.head(5)

### c) How many  records are there in the dataset?

In [ ]:
len(df)

### d) How many columns are there in the dataset?

In [ ]:
len(df.columns)

### e) Print the name of all the columns in the dataset

In [ ]:
print(df.columns)

### f) What is  the name of the 20th column ?

In [ ]:
df.columns[19]

### g) What is  the datatype of each column in the dataset?

In [ ]:
df.dtypes

### h) Display the columns from 5 to 9 and rows from 1 to 3 of the dataset

In [ ]:
# df.iloc[## ROW VALUE SLICING, COLUMN VALUES SCLICING]
df.iloc[0:3, 4:9]

### i) Display all the rows after 50th row of the dataset

In [ ]:
df[50:]

### j) Display the columns from 10 to 12 for first 50 rows of the dataset

In [ ]:
df.iloc[:50, 9:12]

###  k) Display the information of the employees who have  joined in Quarter 1 and 4.

In [ ]:
df.loc[df['Quarter of Joining'].isin(['Q1','Q4'])]

### l) How many people are from the southern region joined on Monday?

In [ ]:
df[df['Region'] == 'South']

In [ ]:
len(df[(df['Region'] == 'South') & (df['DOW of Joining'] == 'Monday')])

In [ ]:
df[(df['Region'] == 'South') & (df['DOW of Joining'] == 'Monday')].shape

### m) Display the information of the employees who have more than 13 years experience in the company

In [ ]:
df[df['Age in Company (Years)'] > 13]

### n) There is a lot of redundant data. For example, the information in the below columns is also available in the *Date of Joining* column.

  1.   month of Joining
  2.   year of Joining
  3.   Day of Joining 

There could be other such columns containing redundant data. Please identify such columns and take appropriate action. 


You can refer to the below link :

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html

In [ ]:
df.drop(columns=['Year of Joining', 'Month of Joining','Day of Joining', 'Short Month'], inplace=True)
df.shape

### o) Remove "%" sign from the "Last % Hike" column values of the dataset

you can refer the below link :

https://stackoverflow.com/questions/52850192/python-extract-last-letter-of-a-string-from-a-pandas-column

In [ ]:
df = df.rename(columns = {'Last % Hike':'Last Hike'})  ### NOT NECESSARY BUT, A VERY ROUTINE QUESTION FROM PARTICIPANTS AT THIS SEGMENT
df['Last Hike'] = [int(each[:-1]) for each in df['Last Hike']]

In [ ]:
# or can also use replace
# df['Last % Hike'] = df['Last % Hike'].str.replace("%"," ")

### p) How many Female employees got hike more than 20% ?

In [ ]:
df[(df['Gender']=='F') & (df['Last Hike'] > 20)]

In [ ]:
# use this when replace is used
df[(df['Gender']=='F') & (df['Last % Hike'].astype(int) > 20)]

### Summary

To know more about Pandas, you can refer below link :

https://www.machinelearningplus.com/python/101-pandas-exercises-python/