In [ ]:
!wget https://raw.githubusercontent.com/mdhabeebvulla/samples/master/Advertising1.csv

--2022-03-06 06:26:03--  https://raw.githubusercontent.com/mdhabeebvulla/samples/master/Advertising1.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4063 (4.0K) [text/plain]
Saving to: ‘Advertising1.csv’

Advertising1.csv    100%[===================>]   3.97K  --.-KB/s    in 0s

2022-03-06 06:26:03 (50.7 MB/s) - ‘Advertising1.csv’ saved [4063/4063]

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('Advertising1.csv')

In [ ]:
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [ ]:
df.shape

(200, 4)

In [ ]:
df.columns

Index(['TV', 'radio', 'newspaper', 'sales'], dtype='object')

In [ ]:
X = df[['TV', 'radio', 'newspaper']]
y = df['sales']

In [ ]:
'''from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X)
X = scaler.transform(X)'''

In [ ]:
X

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()
lr.fit(X_train,y_train)
ypred = lr.predict(X_test)

In [ ]:
df1 = pd.DataFrame({'ActualValues':y_test,'PredictedValues':ypred})
df1

     ActualValues  PredictedValues
100          11.7        13.729750
34            9.5         7.588923
184          17.6        18.570037
56            5.5         8.377007
157          10.1         9.962930
195           7.6         5.322866
171          14.5        14.240746
35           12.8        17.131065
186          10.3         9.623563
135          11.6        14.113102
113          15.9        16.517536
112          14.1        14.007454
71           12.4        10.548650
189           6.7         5.963118
106           7.2         6.002348
73           11.0         9.813313
52           22.6        20.677754
169          15.0        18.092635
88           12.9        11.417763
101          23.8        22.940634
36           25.4        23.649983
51           10.7         9.401374
118          15.9        15.293257
191           9.9         8.461596
154          15.6        15.611428
25           12.0        15.655027
162          14.9        14.957544
151          11.6         9.824748
197          12.8        12.873507
47           23.2        21.868951
143          10.4         8.643830
87           16.0        15.413410
159          12.9        12.328410
131          12.7        15.489795
66            9.5         9.089935
105          19.2        17.811447
108           5.3         3.449814
160          14.4        14.186968
130           1.6        10.490597
179          12.6        12.404612
11           17.4        17.449233
17           24.4        23.178572
46           10.6         8.748773
64           18.0        17.008488
80           11.8        11.437458
72            8.8        10.365661
137          20.8        20.748024
133          19.6        19.229157
44            8.5         8.729521
53           21.2        19.845757
9            10.6        12.548522
8             4.8         3.731007
138           9.6         9.749223
111          21.8        21.251093
22            5.6         6.260641
15           22.4        20.764488
109          19.8        19.879529
196           9.7         8.184615
19           14.6        14.207164
145          10.3         9.739882

In [ ]:
from sklearn.metrics import mean_squared_error
print('RMSE is ',np.sqrt(mean_squared_error(y_test,ypred)))

RMSE is  1.890816106301797